### ISSUE TITLE
make locktime configurable

### ISSUE THREAD

**Issue by dajohi** [decred/atomicswap#17]
locktime is currently hardcoded.  it would be nice to specify locktime.

```go
./cmd/btcatomicswap/main.go:    locktime := time.Now().Add(48 * time.Hour).Unix()
./cmd/btcatomicswap/main.go:    locktime := time.Now().Add(24 * time.Hour).Unix()
./cmd/dcratomicswap/main.go:    locktime := time.Now().Add(48 * time.Hour).Unix()
./cmd/dcratomicswap/main.go:    locktime := time.Now().Add(24 * time.Hour).Unix()
./cmd/ltcatomicswap/main.go:    locktime := time.Now().Add(48 * time.Hour).Unix()
./cmd/ltcatomicswap/main.go:    locktime := time.Now().Add(24 * time.Hour).Unix()
```

**Comment by jrick** [comment]
Going to prevent some foot shooting here.  I don't think these are constants you want to modify.  They need to be relatively long in order to deal with humans being slow/busy and to wait for on-chain transactions to be mined.  In order to actually be atomic and safe the first contract's locktime needs to be much larger than the second's.  Changing these may result in parties not given enough time to perform their redemption and could lead to fraud.

**Comment by jrick** [comment]
closing this for the above reasons until someone can provide a better situation that necessitates it besides "it would be nice".

**Comment by davecgh** [comment]
I would also add that one of the important factors is that the lock time of the initiator's transaction is approximately 2x longer than the lock time of the participant's transaction.

Granted this could be handled automatically along with warning if the time is too low, but I agree with @jrick here.  The defaults are sufficiently long to ensure both parties have ample time to audit the contracts and get their respective transactions mined before the ability to revoke unlocks.

I feel like making this configurable would very likely lead to situations that end up negating the very reason the contract exists to begin with.
