### ISSUE TITLE
Bitcoin Cash support?

### ISSUE THREAD

**Issue by DesWurstes** [decred/atomicswap#19]

**Comment by jrick** [comment]
It probably already works, but is untested.  Give it a try.

**Comment by DesWurstes** [comment]
It looks like it doesn't. [SIGHASH_FORKID](https://github.com/Bitcoin-UAHF/spec/blob/master/replay-protected-sighash.md) needs to be implemented.

**Comment by jrick** [comment]
I want to take a stab at this in my free time, mostly just to make all these "news" sites claiming that atomic swaps require segwit to look dumb :)

So far I have forked the tool and am creating (invalid) signatures with SIGHASH_FORKID set.  The signatures are invalid since this sighash flag completely changes the sighash algorithm and sigs no longer validate.  Next step is to implement the correct FORKID sighash algorithm.

**Comment by DesWurstes** [comment]
Thanks!

**Comment by paOol** [comment]
@jrick I can help test if you need. I have a bitcoin ABC node.

**Comment by coblee** [comment]
This should be a fairly simple fix. Might even want to add a `--cash` option to `btcatomicswap`. That should please the Bitcoin Cash supporters. 😄

**Comment by DesWurstes** [comment]
Do you need help?
