### ISSUE TITLE
Transaction fees

### ISSUE THREAD

**Issue by artfully64** [decred/atomicswap#28]
Hi! Having a question about transaction fee. Can a dev set it up as desired or is it a fixed amount?

**Comment by jrick** [comment]
For dcratomicswap it is hardcoded.  For all of the other tools, it will first check to see if a fee rate was explicitly set by the user for their wallet (using settxfee), and if so, it will use this instead of trying to estimate an appropriate fee (which may fail, causing it to fallback to the minimum relay fee policy).

So if you want to force a fee rate, just use settxfee on the wallet the tool is talking to.

**Comment by jrick** [comment]
I would also consider adding a flag to all of the tools which overrides even any fee set by settxfee.

**Comment by jrick** [comment]
Closing due to age
